# Generated by Django 2.0 on 2020-03-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colacion',
            fields=[
                ('idcolacion', models.AutoField(db_column='idColacion', primary_key=True, serialize=False)),
                ('entrada', models.CharField(blank=True, db_column='Entrada', max_length=45, null=True)),
                ('entrada_descripcion', models.CharField(blank=True, db_column='Entrada_Descripcion', max_length=255, null=True)),
                ('principal', models.CharField(blank=True, db_column='Principal', max_length=45, null=True)),
                ('principa_descripcion', models.CharField(blank=True, db_column='Principa_Descripcion', max_length=255, null=True)),
                ('postre', models.CharField(blank=True, db_column='Postre', max_length=45, null=True)),
                ('postre_descripcion', models.CharField(blank=True, db_column='Postre_Descripcion', max_length=255, null=True)),
                ('precio', models.IntegerField(blank=True, db_column='Precio', null=True)),
                ('precio_sin_postre', models.IntegerField(blank=True, db_column='Precio_sin_postre', null=True)),
                ('dia', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'colacion',
                'managed': False,
            },
        ),
    ]
