# Generated by Django 2.0 on 2020-03-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chef', '0002_auto_20200315_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almuerzos',
            fields=[
                ('almuerzos_id', models.AutoField(db_column='Almuerzos_id', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=45, null=True)),
                ('opcion', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'db_table': 'Almuerzos',
                'managed': False,
            },
        ),
    ]
