# Generated by Django 2.0 on 2020-04-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chef', '0003_almuerzos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('clases_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=400)),
                ('ingredientes', models.CharField(db_column='Ingredientes', max_length=400)),
                ('pagado', models.IntegerField(db_column='Pagado')),
            ],
            options={
                'db_table': 'Clases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscritosClase',
            fields=[
                ('insc_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=55, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=55, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=55, null=True)),
                ('pagado', models.IntegerField(db_column='Pagado')),
            ],
            options={
                'db_table': 'Inscritos_clase',
                'managed': False,
            },
        ),
    ]
