# Generated by Django 2.0 on 2020-04-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_chef', '0004_clases_inscritosclase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clases',
            options={},
        ),
    ]
